"""third migration

Revision ID: 20305e10c8f0
Revises: 0f206db95c22
Create Date: 2024-12-06 16:34:36.299984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20305e10c8f0'
down_revision = '0f206db95c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stripe_payment_id', sa.String(length=120), nullable=False))
        batch_op.create_foreign_key('None', 'user', ['customer_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=True))
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('name')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('None', type_='foreignkey')
        batch_op.drop_column('stripe_payment_id')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
